name: CI (global konveyor CI)

on:
  push:
    branches:
      - "main"

  pull_request:
    paths-ignore:
      - "docs/**"
      - "hack/**"
      - "*.md"
    branches:
      - "main"

  workflow_call:

###
# The global CI settings need to be adjusted for the `release-*`` branches such that:
#  1. The operator uses the correct `:release-*` images
#  2. The `*-tests_ref` use the correct branches
#
# on:
#   push:
#     branches:
#       - 'main'
#       - 'release-*'
#
#   pull_request:
#     branches:
#       - 'main'
#       - 'release-*'
##

concurrency:
  group: ci-global-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload-for-global-ci:
    runs-on: ubuntu-latest
    outputs:
      IMG_NAME: ${{ steps.container.outputs.IMG_NAME }}
    steps:
      - uses: actions/checkout@v4

      - id: container
        name: build the tackle2-ui container
        env:
          IMG_NAME: ttl.sh/tackle2-ui-${{ github.sha }}:2h
        run: |
          echo "IMG_NAME=${IMG_NAME}" >> "$GITHUB_OUTPUT"
          docker build . -t ${IMG_NAME}
          docker push ${IMG_NAME}

  determine-ui-tests-ref:
    runs-on: ubuntu-latest
    outputs:
      ui_tests_ref: ${{ steps.determine-ref.outputs.ui_tests_ref }}
    steps:
      - name: Determine what git ref to use for the UI tests
        id: determine-ref
        run: |
          echo "For push events: uses branch ref (refs/heads/BRANCH)"
          echo "For PR events: uses PR merge ref (refs/pull/NUMBER/merge)"
          echo "ui_tests_ref=${{ github.ref }}"
          echo "ui_tests_ref=${{ github.ref }}" >> "$GITHUB_OUTPUT"
          echo "Using \`ui_tests_ref=${{ github.ref }}\`" >> "$GITHUB_STEP_SUMMARY"

  run-global-ci:
    needs: [build-and-upload-for-global-ci, determine-ui-tests-ref]
    uses: konveyor/ci/.github/workflows/global-ci-bundle.yml@main
    with:
      tackle_ui: ${{ needs.build-and-upload-for-global-ci.outputs.IMG_NAME }}
      run_api_tests: false
      run_ui_tests: true
      ui_test_tags: "@ci"
      ui_tests_ref: ${{ needs.determine-ui-tests-ref.outputs.ui_tests_ref }}
