name: CI (global konveyor CI)

on:
  push:
    branches:
      - "main"

  pull_request:
    paths-ignore:
      - "docs/**"
      - "hack/**"
      - "*.md"
    branches:
      - "main"

  workflow_call:

###
# The global CI settings need to be adjusted for the `release-*`` branches such that:
#  1. The operator uses the correct `:release-*` images
#  2. The `*-tests_ref` use the correct branches
#
# on:
#   push:
#     branches:
#       - 'main'
#       - 'release-*'
#
#   pull_request:
#     branches:
#       - 'main'
#       - 'release-*'
##

concurrency:
  group: ci-global-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload-for-global-ci:
    runs-on: ubuntu-latest
    outputs:
      IMG_NAME: ${{ steps.container.outputs.IMG_NAME }}
    steps:
      - uses: actions/checkout@v4

      - id: container
        name: build the tackle2-ui container
        env:
          IMG_NAME: ttl.sh/tackle2-ui-${{ github.sha }}:2h
        run: |
          echo "IMG_NAME=${IMG_NAME}" >> "$GITHUB_OUTPUT"
          docker build . -t ${IMG_NAME}
          docker push ${IMG_NAME}

  run-global-ci:
    needs: build-and-upload-for-global-ci
    uses: konveyor/ci/.github/workflows/global-ci-bundle.yml@main
    with:
      tackle_ui: ${{ needs.build-and-upload-for-global-ci.outputs.IMG_NAME }}
      run_api_tests: false
      run_ui_tests: true
