name: e2e - run tier0 tests for cypress test changes on push to main

on:
  push:
    branches:
      - main
    paths:
      - "cypress/**"

concurrency:
  group: tier0-push-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main-tier0:
    uses: ./.github/workflows/e2e-run-ui-tests.yaml
    with:
      test_tags: "@ci,@tier0"
      feature_auth_required: true
      bundle_image: quay.io/konveyor/tackle2-operator-bundle:latest
      install_konveyor_version: main
      test_ref: main
