name: Nightly CI (repo level @release-0.9)

on:
  schedule:
    - cron: "35 5 * * *" # every day @ 5:35am UTC

  workflow_dispatch:

jobs:
  nightly:
    uses: konveyor/tackle2-ui/.github/workflows/ci-repo.yml@release-0.9
    secrets: inherit
    with:
      checkout_ref: release-0.9
